export const SPEAKER_ITEMS = [
  { label: "1학년 1반", status: "on" as const },
  { label: "1학년 2반", status: "on" as const },
  { label: "1학년 3반", status: "on" as const },
  { label: "1학년 4반", status: "on" as const },
  { label: "별관 1-1", status: "off" as const },
  { label: "2학년 1반", status: "on" as const },
  { label: "2학년 2반", status: "on" as const },
  { label: "2학년 3반", status: "on" as const },
  { label: "2학년 4반", status: "on" as const },
  { label: "별관 1-2", status: "off" as const },
  { label: "3학년 1반", status: "on" as const },
  { label: "3학년 2반", status: "on" as const },
  { label: "3학년 3반", status: "on" as const },
  { label: "3학년 4반", status: "on" as const },
  { label: "별관 1-3", status: "off" as const },
  { label: "선생 영역", status: "off" as const },
  { label: "시청각실", status: "off" as const },
  { label: "체육관", status: "off" as const },
  { label: "보건실", status: "off" as const },
  { label: "별관 2-1", status: "off" as const },
  { label: "교무실", status: "off" as const },
  { label: "과학실", status: "off" as const },
  { label: "강당", status: "off" as const },
  { label: "방송실", status: "error" as const },
  { label: "별관 2-2", status: "off" as const },
  { label: "지문등고", status: "off" as const },
  { label: "무등12", status: "off" as const },
  { label: "경이포구", status: "off" as const },
  { label: "옥의", status: "off" as const },
  { label: "운동장", status: "off" as const },
];
